const ACTIONS_PREFIX = 'CounterContext';
export const INCREASE = `${ACTIONS_PREFIX}/INCREASE`;
export const DECREASE = `${ACTIONS_PREFIX}/DECREASE`;
export const SET_COUNTER = `${ACTIONS_PREFIX}/SET_COUNTER`;
export const ASYNC_INCREASE_START = `${ACTIONS_PREFIX}/ASYNC_INCREASE_START`;
export const ASYNC_INCREASE_END = `${ACTIONS_PREFIX}/ASYNC_INCREASE_END`;
export const ASYNC_INCREASE_ERROR = `${ACTIONS_PREFIX}/ASYNC_INCREASE_ERROR`;
